### PR TITLE
iptables: Move ports logic to define

### PR DESCRIPTION
**Pull request by jeefberkey**
This commit moves the logic that parses the `iptables::ports` hash into a define, to make it possible to use the same hash format in other modules without copying code. 

There was also a bug where compilation would fail if `proto` was specified in the defaults section of the hash.

### CODE REVIEW

**Comment by jeefberkey** [comment]
✔️ https://gitlab.com/simp/pupmod-simp-iptables/pipelines/16466079

**Comment by trevor-vaughan** [comment]
@jeefberkey I've got an update coming in for this that should fix the issues with Kubernetes.

**Comment by jeefberkey** [comment]
@trevor-vaughan This PR isn't related to SIMP-4328

**Comment by trevor-vaughan** [comment]
Closes SIMP-4328

**Comment by trevor-vaughan** [comment]
Would like a review from @jeefberkey prior to final push.

**Comment by jeefberkey** [comment]
Changes work for me so far, in the case that was documented in SIMP-4328.

**Pull request merged**
