### PR TITLE
(SIMP-8691) Does not manage service when use_firewalld=true on EL6

### PR DESCRIPTION
**Pull request by lnemsick-simp**
- Fixed a bug in which the iptables services and rules were not
  managed when iptables::use_firewalld was set to true on an
  EL6 system.
- Maintenance
  - Removed unit test cruft left over from experimental firewalld
    support.
  - Split out firewalld suite into its own tests in the .gitlab-ci.yml
    so that individual test suite status could be more easily tracked.

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
marked as WIP because the oel tests are now actually doing something and failing

**Comment by lnemsick-simp** [comment]
Pushing off the OEL problems to a separate ticket https://simp-project.atlassian.net/browse/SIMP-8694

**Comment by lnemsick-simp** [comment]
Non-OEL tests are passing: https://gitlab.com/simp/pupmod-simp-iptables/-/pipelines/217320999

**Comment by lnemsick-simp** [comment]
https://gitlab.com/simp/pupmod-simp-iptables/-/pipelines/217452118

**Review by trevor-vaughan — APPROVED** [review]

**Pull request merged**
